### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ajan-12** [Age-of-Elysian/SlimefunFix#1]
> [21:20:04] [Server thread/INFO]: ajan_12 issued server command: /sffix
> [21:20:04] [Server thread/INFO]: Tried to fix items but none found.
> [21:20:04] [Server thread/ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'sffix' in plugin SlimefunFix v1
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
> 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	at java.lang.Thread.run(Unknown Source) [?:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
> 	at top.ageofelysian.SlimefunFix.SlimefunFix.onCommand(SlimefunFix.java:119) ~[?:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
> 	... 15 more

**Comment by yhdesai** [comment]
Please add a small description of the issue in the title instead of just saying help

**Comment by ajan-12** [comment]
Need help in fixing the issue

**Comment by ajan-12** [comment]
There's no info

**Comment by AlexLander123** [comment]
You forgot a return statement for this else condition. You need to return true after line 107.
https://github.com/Age-of-Elysian/SlimefunFix/blob/8f62a6775bcceccb039058ab3b663d1df93ca420/SlimefunFix/src/main/java/top/ageofelysian/SlimefunFix/SlimefunFix.java#L101-L108
